Resources:
  ApiGatewayAuthorizer: 
    DependsOn:
      - ApiGatewayRestApi
    Type: AWS::ApiGateway::Authorizer
    Properties: 
      AuthorizerResultTtlInSeconds: 300
      IdentitySource: method.request.header.Authorization
      RestApiId:
        Ref: ApiGatewayRestApi
      Type: COGNITO_USER_POOLS
      Name: Authorizer
      ProviderARNs: 
        - Fn::Join:
          - ''
          - - 'arn:aws:cognito-idp:'
            - ${self:provider.region}
            - ':'
            - Ref: AWS::AccountId
            - ':userpool/'
            - Ref: CognitoUserPool
