Resources:
  DefaultsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: '${self:service}-${self:provider.stage}-defaults'
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
