Resources:
  DynamoDBIamPolicy:
    Type: 'AWS::IAM::Policy'
    DependsOn:
    Properties:
      PolicyName: lambda-dynamodb
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
      Roles:
        - Ref: IamRoleLambdaExecution
