service: <%= name %>
provider:
  name: aws
  runtime: nodejs8.10
  stage: '${opt:stage, ''dev''}'
  region: eu-central-1
  profile: default
  timeout: 30
  environment:
    STAGE: '${self:provider.stage}'
resources:
  Resources:
    DynamoDBIamPolicy:
      Type: 'AWS::IAM::Policy'
      DependsOn:
        - DefaultsTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:Scan'
                - 'dynamodb:GetItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:DeleteItem'
              Resource: 'arn:aws:dynamodb:*:*:table/${self:provider.stage}-defaults'
        Roles:
          - Ref: IamRoleLambdaExecution
    DefaultsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: '${self:provider.stage}-defaults'
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
functions:
  defaultFunction:
    name: '${self:provider.stage}-defaultFunction'
    handler: handler.defaultFunction
    memorySize: 128
    events:
      - http:
          path: defaults
          method: any
          cors: true
