service: <%= serviceName %>
provider:
  name: aws
  runtime: nodejs8.10
  stage: '${opt:stage, ''dev''}'
  region: eu-central-1
  profile: default
  timeout: 30
  environment:
    STAGE: '${self:provider.stage}'
    APP: '${self:service}'
resources:
  - '${file(config/resources/cognito-user-pool.yml)}'
  - '${file(config/resources/cognito-user-pools-authorizer.yml)}'
  - '${file(config/resources/cognito-identity-pool.yml)}'
  - '${file(config/resources/dynamodb-iam-policy.yml)}'
functions:
